### ISSUE TITLE
[2.6] Changing viewmodel FOV causes weapon effects to go off

### ISSUE THREAD

**Issue by ry13y04** [phoenixprojectsoftware/zamnhlmp#24]
`cl_viewmodel_fov 0`
![1](https://user-images.githubusercontent.com/75205875/132099876-d13f402a-ab38-4702-bfe2-f490b749668d.png)
`cl_viewmodel_fov 150` [any value]
![2](https://user-images.githubusercontent.com/75205875/132099890-4c32b45a-de47-4980-8ff1-9839a9b7bb93.png)

**Comment by sabianroberts** [comment]
Didn't notice this [guess I never used viewmodel FOV enough]. Thanks for reporting! There's been loads of commits over at [OpenAG](https://github.com/YaLTeR/OpenAG) so maybe those folks fixed it
