### ISSUE TITLE
More Domination map support

### ISSUE THREAD

**Issue by ry13y04** [phoenixprojectsoftware/zamnhlmp#80]
- [x] Base
- [x] Boot Camp
- [x] Bounce, Bounce Day and Walk
- [x] Bounfire
- [x] City
- [x] Crossfire, Crossfire Day and Corssfire
- [x] CZ2
- [x] Datacore
- [x] Demise
- [ ] Disposal (?)
- [x] Doublecross
- [x] Doublefort
- [ ] Dustbowl
- [x] Dyce
- [x] Flashback
- [x] Frenzy
- [x] Gasworks (?)
- [x] Kasino
- [x] Kasino2
- [ ] Kndyone
- [x] Lambda Bunker
- [x] Outpost
- [x] Park
- [x] Rapidcore
- [x] Rubble
- [x] Snark Pit
- [x] StalkX
- [x] Stalkyard
- [x] Subtransit and Subtarnsit
- [x] Undertow

**Comment by sabianroberts** [comment]
NAHH DAWG WE CAN'T DO DAT 😭😭😭😭😭😭
